version: '3'

services:
  webapp:
    build: .
    ports:
      - ${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: ['--port', '${WEB_CLIENT_PORT}']
    restart: always
